# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'de.hosting-rt.homeassistant-plugin'

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: de.hosting-rt.homeassistant-plugin
    - run: npm ci
    - run: npm run build
    - run: mv plugin de.hosting-rt.homeassistant-plugin.sdPlugin
  
    - name: Zip Folder
      run: zip -r plugin.zip . -x "dist/*" "src/*" "*.json" "node_modules/*" ".gitignore"
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: de.hosting-rt.homeassistant-plugin/release.zip
        asset_name: plugin.zip
        tag: ${{ github.ref }}
        overwrite: true
    
