# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'de.hosting-rt.homeassistant-plugin'

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: de.hosting-rt.homeassistant-plugin
    - run: npm ci
    - run: npm run build
    - run: mv plugin de.hosting-rt.homeassistant-plugin.sdPlugin
  
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'release.zip'
        directory: 'de.hosting-rt.homeassistant-plugin'
        exclusions: 'dist/* src/* *.json .gitignore node_modules/*'

    
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          release.zip
    
